// export const GET_CART_REQUEST = "GET_CART_REQUEST"
// export const GET_CART_FAILURE = "GET_CART_FAILURE"
// export const GET_CART_SUCCESS = "GET_CART_SUCCESS"

// export const ADD_CART_REQUEST = "ADD_CART_REQUEST"
// export const ADD_CART_FAILURE = "ADD_CART_FAILURE"
// export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"

// export const REMOVE_CART_REQUEST = "REMOVE_CART_REQUEST"
// export const REMOVE_CART_FAILURE = "REMOVE_CART_FAILURE"
// export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS"

// export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
// export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE"
// export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"

export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const REMOVE_ITEM = "REMOVE_ITEM";